import { z } from 'zod';

import { directionSchema, displayStringSchema } from './common';

/**
 * One session on the five-day trend strip the iOS tile draws along its bottom
 * edge (plan `2026-08-22-ios-five-day-trend-lights`).
 *
 * `level` is a small INTEGER, not a ratio and not an intensity: the strip
 * carries direction in colour and magnitude in HEIGHT, and there is
 * deliberately no field here a renderer could reach for to tint or fade a
 * mark. Four discrete steps, graded server-side from absolute percentage
 * thresholds (`src/lib/trend/trend-scale.ts`). Those thresholds are identical
 * for every instrument WITHIN an asset class, so two tiles side by side are
 * comparable — but equities and options are graded on different bands, because
 * a 3% day is a big one for a share and a dull one for an option premium, and
 * one scale across both pegs every option bar at full height.
 *
 * `pct` is display output for the accessibility phrase and nothing else — it
 * is never parsed back, the same rule every other formatted field here lives
 * under.
 */
export const trendDaySchema = z.object({
  /** The session's calendar date, 'YYYY-MM-DD'. */
  date: z.string(),
  direction: directionSchema,
  /** 0 = flat, 3 = full height. */
  level: z.number().int().min(0).max(3),
  pct: displayStringSchema,
});

export type TrendDayContract = z.output<typeof trendDaySchema>;

/**
 * The strip as it rides the wire: at most five sessions, OLDEST FIRST, so the
 * array index is the column index and the view does no reversing.
 *
 * Entries are NULLABLE, and a null is not a flat day. A flat day is a fact —
 * the session happened and the price went nowhere — and it arrives as a graded
 * entry with `level: 0`. A null is the absence of a fact: nothing was recorded
 * for that session, or the only two figures available for it were different
 * KINDS of number (a model mark against a real traded close, which is a change
 * of measuring instrument rather than a return). Collapsing the two would have
 * the tile assert that a contract sat still on a day it never traded.
 *
 * Deliberately NOT named `*Schema`: `scripts/gen-swift-contracts.mjs` registers
 * every export whose name ends in `Schema` as a Swift TYPE of its own, and an
 * optional array is a field shape, not a type. `TrendDay` is the type; this is
 * how the two carriers spell the field.
 *
 * OPTIONAL, and that is an upgrade-path decision rather than laziness. The
 * Swift structs are generated by quicktype, which emits a non-optional `let`
 * for a required field — so a required `trend` would make the PREVIOUS
 * build's on-disk snapshot (`Snapshot` in `LiveStore.swift`, `CachedWatchlist`
 * in `WatchlistStore.swift`) fail to decode on the first launch after an
 * upgrade, throwing away a working cached Dashboard to gain a strip that was
 * arriving with the next request anyway. Absent degrades to "no strip", which
 * every surface already handles.
 */
export const trendDaysField = z.array(trendDaySchema.nullable()).max(5).optional();
